# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac2071751b5e2548f94fa5e7e958351e824d9f9912a2dfa638be229ae3ba9913c736b3355d08c0344717d6193d4f01187f3bf3da3195b70ec64b00c2cc0360b0

test:
  secret_key_base: df947a6f171118113b03bf6229fbba900443844a6caaeeb6d84b6fccad1a043380f97b868bd6d2f50bfa0b7010310892bf3a4824aa1f9e33e323228a90dfd88a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
